spring.application.name=notification-service
server.port=8082

spring.kafka.bootstrap-servers=localhost:29092
spring.kafka.consumer.group-id=notification-service
spring.kafka.consumer.auto-offset-reset=earliest

app.kafka.topic.order-created=orders.created
